### PR TITLE
initial pr: media/colors textures updates

### PR DESCRIPTION
**Pull request by un1versal**
These are textures from https://github.com/un1versal/revamped.themes/tree/revamp

There's a handy table to know what the differences are what to expect thats not on the default,  
see [What-should I Expect to See Changed](https://github.com/un1versal/revamped.themes/tree/revamp#what-should-you-expect-to-see-changed)

These textures are from the revamped themes in blue and is 100% replacement for confluences er I mean MrMC skin.

The only thing I did not replace was the SKINDEFAULT wallpaper here but if you are interested in mine its this simple one revamped

@davilla as I explained if you guys want to test drive this feel free to use https://github.com/un1versal/revamped.themes/releases/tag/5.05 it will work 100% without any permanent changes.

if you guys prefer to these as additional themes thats OK too

I can add or remove or customize graphics just let me know what you prefer.

### CODE REVIEW

**Comment by MrMC** [comment]
thx, will test when have the time.

**Comment by un1versal** [comment]
The touch skin can have the same treatment pretty much.

**Comment by un1versal** [comment]
Any news, thoughts, comments, feedback or *something*? this tumbleweed business is not profitable.

**Comment by MrMC** [comment]
Working on lots of things, themes being one of them. Also realwork(tm) priorities rule.

**Comment by MrMC** [comment]
merged for 1.2.x testflight and future 1.3.0 release

**Comment by un1versal** [comment]
funny merge... this was closed ;) thx

**Comment by MrMC** [comment]
We pull in directly, I dislike the merge commit that github does. Makes the actual commit hard to see and track.

**Comment by un1versal** [comment]
rebase then

**Comment by MrMC** [comment]
That won't work unless force push into master which we will not do. This via is green button hit on github.
Also it does not show up here (this repo) until we push private repo into public on release.

**Comment by un1versal** [comment]
absolutely no force push required and works with rebase, then just normal push will do

read http://kernowsoul.com/blog/2012/06/20/4-ways-to-avoid-merge-commits-in-git/

You take a PR that is fully rebased against the branch intend to merge something and add the person whos doing pr as a remote, the git pull --rebase their feature branch work ontop of the branch youre merging into and then push. done

it would appear as a single commit ontop of master or whatever and nothing is forced into anywhere.

works ;)

**Comment by MrMC** [comment]
Github's green button does not work that way :)

**Comment by un1versal** [comment]
who cares about github green button :p hehehe

**Comment by MrMC** [comment]
not me :) I'm just saying it was merged for 1.2.x testflight and future 1.3.0 release. The actual commits will not show up in the public repo until 1.3 is released.

**Comment by un1versal** [comment]
Yes I got it when you said it before.  its an odd way to work but hey...

So you like changes? ideally the OSK keys would be made white when selected for better visibility but that skin changes alone dont do the trick and I couldnever find the c++ for it.

**Comment by MrMC** [comment]
seems ok to me, the real test is what users say.

**Comment by un1versal** [comment]
:) haters will hate :) lovers will love and everyone else in a pile wondering where the popcorn is. 

let me know.

**Pull request closed without merging**
